CREATE TABLE IF NOT EXISTS toko_schema(version integer PRIMARY KEY, applied_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS users(id uuid PRIMARY KEY, username text UNIQUE NOT NULL, password_hash text NOT NULL, role text NOT NULL DEFAULT 'learner', must_change_password boolean NOT NULL DEFAULT false, profile jsonb NOT NULL DEFAULT '{"level":"Pre-A1","daily_minutes":30,"thai_support":true,"voice":"Kore","speed":1,"monthly_budget":600,"live_minutes":10,"onboarded":false}', created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS auth_sessions(token_hash text PRIMARY KEY, user_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE, expires_at timestamptz NOT NULL);
CREATE TABLE IF NOT EXISTS invitations(id uuid PRIMARY KEY, token_hash text UNIQUE NOT NULL, created_by uuid NOT NULL REFERENCES users(id), expires_at timestamptz NOT NULL, used_by uuid REFERENCES users(id), revoked boolean NOT NULL DEFAULT false, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS lessons(id text PRIMARY KEY, ordinal integer UNIQUE NOT NULL, data jsonb NOT NULL);
CREATE TABLE IF NOT EXISTS scenarios(id text PRIMARY KEY, user_id uuid REFERENCES users(id) ON DELETE CASCADE, data jsonb NOT NULL, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS learning_sessions(id uuid PRIMARY KEY, user_id uuid NOT NULL REFERENCES users(id), lesson_id text REFERENCES lessons(id), scenario_id text REFERENCES scenarios(id), mode text NOT NULL, status text NOT NULL DEFAULT 'active', state jsonb NOT NULL DEFAULT '{"stage":"pattern","hint_level":0,"step":0}', summary jsonb, model_version text NOT NULL, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS turns(id uuid PRIMARY KEY, session_id uuid NOT NULL REFERENCES learning_sessions(id), role text NOT NULL, text text NOT NULL, audio_id uuid, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS attempts(id uuid PRIMARY KEY, session_id uuid NOT NULL REFERENCES learning_sessions(id), user_id uuid NOT NULL REFERENCES users(id), request_id text NOT NULL, input_kind text NOT NULL, transcript text NOT NULL, feedback jsonb NOT NULL, hint_level integer NOT NULL DEFAULT 0, duration_seconds float NOT NULL DEFAULT 0, retry_of uuid REFERENCES attempts(id), audio_id uuid, created_at timestamptz NOT NULL DEFAULT now(), UNIQUE(user_id, request_id));
CREATE TABLE IF NOT EXISTS review_items(id uuid PRIMARY KEY, user_id uuid NOT NULL REFERENCES users(id), key text NOT NULL, kind text NOT NULL, prompt text NOT NULL, target text NOT NULL, meaning text NOT NULL DEFAULT '', stage integer NOT NULL DEFAULT 0, due_at timestamptz NOT NULL DEFAULT now(), failures integer NOT NULL DEFAULT 0, source_attempt uuid REFERENCES attempts(id), UNIQUE(user_id,key));
CREATE TABLE IF NOT EXISTS review_events(id uuid PRIMARY KEY, user_id uuid NOT NULL REFERENCES users(id), item_id uuid NOT NULL REFERENCES review_items(id), request_id text NOT NULL, result jsonb NOT NULL, created_at timestamptz NOT NULL DEFAULT now(), UNIQUE(user_id,request_id));
CREATE TABLE IF NOT EXISTS mastery(user_id uuid NOT NULL REFERENCES users(id), lesson_id text NOT NULL REFERENCES lessons(id), independent_successes integer NOT NULL DEFAULT 0, assisted_successes integer NOT NULL DEFAULT 0, completed boolean NOT NULL DEFAULT false, updated_at timestamptz NOT NULL DEFAULT now(), PRIMARY KEY(user_id,lesson_id));
CREATE TABLE IF NOT EXISTS vocabulary(id uuid PRIMARY KEY, user_id uuid NOT NULL REFERENCES users(id), term text NOT NULL, meaning text NOT NULL, example text NOT NULL, uses integer NOT NULL DEFAULT 0, created_at timestamptz NOT NULL DEFAULT now(), UNIQUE(user_id,term));
CREATE TABLE IF NOT EXISTS audio_assets(id uuid PRIMARY KEY, user_id uuid REFERENCES users(id), cache_key text UNIQUE, path text NOT NULL, mime text NOT NULL, expires_at timestamptz, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS usage(id uuid PRIMARY KEY, user_id uuid NOT NULL REFERENCES users(id), session_id uuid REFERENCES learning_sessions(id), role text NOT NULL, model text NOT NULL, status text NOT NULL DEFAULT 'reserved', reserved_thb numeric NOT NULL, cost_thb numeric NOT NULL DEFAULT 0, input_tokens integer NOT NULL DEFAULT 0, output_tokens integer NOT NULL DEFAULT 0, audio_input_tokens integer NOT NULL DEFAULT 0, audio_output_tokens integer NOT NULL DEFAULT 0, latency_ms integer NOT NULL DEFAULT 0, live_seconds integer NOT NULL DEFAULT 0, price_snapshot jsonb NOT NULL, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS jobs(id uuid PRIMARY KEY, user_id uuid NOT NULL REFERENCES users(id), kind text NOT NULL, request_key text NOT NULL, payload jsonb NOT NULL, status text NOT NULL DEFAULT 'queued', result jsonb, error text, attempts integer NOT NULL DEFAULT 0, available_at timestamptz NOT NULL DEFAULT now(), locked_at timestamptz, created_at timestamptz NOT NULL DEFAULT now(), UNIQUE(user_id,request_key));
CREATE TABLE IF NOT EXISTS live_tickets(token_hash text PRIMARY KEY, session_id uuid NOT NULL REFERENCES learning_sessions(id), user_id uuid NOT NULL REFERENCES users(id), expires_at timestamptz NOT NULL, consumed boolean NOT NULL DEFAULT false);
CREATE UNIQUE INDEX IF NOT EXISTS one_running_tts ON jobs(user_id,request_key);
CREATE INDEX IF NOT EXISTS due_reviews ON review_items(user_id,due_at);
CREATE INDEX IF NOT EXISTS user_usage_month ON usage(user_id,created_at);
CREATE INDEX IF NOT EXISTS session_turns ON turns(session_id,created_at);
CREATE INDEX IF NOT EXISTS runnable_jobs ON jobs(status,available_at);
INSERT INTO toko_schema(version) VALUES(1) ON CONFLICT DO NOTHING;

CREATE TABLE IF NOT EXISTS speech_events(id uuid PRIMARY KEY, user_id uuid NOT NULL REFERENCES users(id), source text NOT NULL, duration_seconds float NOT NULL, created_at timestamptz NOT NULL DEFAULT now());
ALTER TABLE review_items ADD COLUMN IF NOT EXISTS hint_until timestamptz;

ALTER TABLE attempts ADD COLUMN IF NOT EXISTS response_ms integer NOT NULL DEFAULT 0;
CREATE TABLE IF NOT EXISTS hint_cache(key text PRIMARY KEY, data jsonb NOT NULL, expires_at timestamptz NOT NULL);
